services:
  database:
    container_name: database
    restart: unless-stopped
    env_file: .env
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMINPASSWORD}
      MYSQL_DATABASE: ${STRAPIDATABASENAME}
      MYSQL_USER: ${STRAPIUSER}
      MYSQL_PASSWORD: ${STRAPIPASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - strapi

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: 'azurite'
    hostname: azurite
    restart: always
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
    volumes:
      - storage-data:/data/

volumes:
  mysql-data:
  storage-data:

networks:
  strapi:
    name: strapi
    driver: bridge
