services:
  database:
    container_name: database
    restart: unless-stopped
    env_file: .env
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMINPASSWORD}
      MYSQL_DATABASE: ${STRAPIDATABASENAME}
      MYSQL_USER: ${STRAPIUSER}
      MYSQL_PASSWORD: ${STRAPIPASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - strapi

  init-database:
    container_name: init-database
    build:
      dockerfile: Dockerfile.database
      context: .
    env_file: .env
    environment:
      ADMINPASSWORD: ${ADMINPASSWORD}
      SERVER: database
      STRAPIUSER: ${STRAPIUSER}
      STRAPIPASSWORD: ${STRAPIPASSWORD}
      STRAPIDATABASENAME: ${STRAPIDATABASENAME}
    networks:
      - strapi
    depends_on:
      database:
        condition: service_healthy

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: 'azurite'
    hostname: azurite
    restart: always
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
    volumes:
      - storage-data:/data/

volumes:
  mysql-data:
  storage-data:

networks:
  strapi:
    name: strapi
    driver: bridge
