#! /bin/sh

psql -d "postgresql://$ADMINUSER:$ADMINPASSWORD@$SERVER/postgres" -c "CREATE USER $STRAPIUSER WITH PASSWORD '$STRAPIPASSWORD';"
psql -d "postgresql://$ADMINUSER:$ADMINPASSWORD@$SERVER/postgres" -c "GRANT CONNECT ON DATABASE $STRAPIDATABASENAME TO $STRAPIUSER;"
psql -d "postgresql://$ADMINUSER:$ADMINPASSWORD@$SERVER/postgres" -c "GRANT CREATE ON DATABASE $STRAPIDATABASENAME TO $STRAPIUSER;"
psql -d "postgresql://$STRAPIUSER:$STRAPIPASSWORD@$SERVER/$STRAPIDATABASENAME" -c "CREATE SCHEMA $STRAPIUSER AUTHORIZATION $STRAPIUSER;"
