name: Infrastructure workflow
run-name: ${{ github.actor }} is running the infrastructure workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  Infrastructure:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show subscription details
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Deploy infrastructure
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region: germanywestcentral
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./deploy/infrastructure.bicep
          parameters: environment=production
          failOnStdErr: false

  Database:
    runs-on: ubuntu-latest
    needs: Infrastructure
    environment: production
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show subscription details
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Deploy database
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region: germanywestcentral
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./deploy/database.bicep
          parameters: environment=production
          failOnStdErr: false
