name: PR workflow
run-name: ${{ github.actor }} is building the cms

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
      id-token: write
      contents: read
jobs:
  ci:
    runs-on: ubuntu-latest
    environment: preview
    name: CI
    if: github.event.action != 'closed'
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 11

      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Deploy cms
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region: westeurope
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./deploy/main.bicep
          parameters: applicationTag=${{ env.GITHUB_REF_NAME_SLUG }} postgresAdministratorLogin=${{ secrets.POSTGRES_ADMINISTRATORLOGIN }} postgresAdministratorLoginPassword=${{ secrets.POSTGRES_ADMINISTRATORLOGIN_PASSWORD }}
          failOnStdErr: false

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: zip code
        run: |
          zip -r strapi.zip .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-xprtzbv-cms-${{ env.GITHUB_REF_NAME_SLUG }}'
          package: strapi.zip

      - name: logout
        run: |
          az logout

  remove_webapp:
    runs-on: ubuntu-latest
    environment: preview
    name: Remove webapp
    if: github.event.action == 'closed'
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 11

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Remove webapp
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az webapp delete -g rg-xprtzbv-website -n app-xprtzbv-cms-${{ env.GITHUB_REF_NAME_SLUG }}

      - name: logout
        run: |
          az logout
