name: Preview workflow
run-name: ${{ github.actor }} is deploying the cms to preview

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write
jobs:
  Preview:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show subscription details
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Deploy cms
        uses: azure/arm-deploy@v2
        with:
          scope: subscription
          region: germanywestcentral
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./deploy/main.bicep
          failOnStdErr: false
